robot_name: piper_arm

# Detector used to teleoperate the robot
detector:
  _target_: openteach.components.detector.oculus.OculusVRHandDetector
  host: ${host_address}
  oculus_port: ${oculus_reciever_port}
  keypoint_pub_port: ${keypoint_port}
  button_port: ${resolution_button_port}
  button_publish_port: ${resolution_button_publish_port}
  teleop_reset_port: ${teleop_reset_port}
  teleop_reset_publish_port: ${teleop_reset_publish_port}

# Transformation classes used to transform the keypoints
transforms:
  - 
    _target_: openteach.components.detector.keypoint_transform.TransformHandPositionCoords
    host: ${host_address}
    keypoint_port: ${keypoint_port}
    transformation_port: ${transformed_position_keypoint_port}
    moving_average_limit: 1

# Visualizers used to visualize the keypoints stream
visualizers:
  -
    _target_: openteach.components.visualizers.visualizer_2d.Hand2DVisualizer
    host: ${host_address}
    transformed_keypoint_port: ${transformed_position_keypoint_port}
    oculus_feedback_port: ${oculus_graph_port}
    display_plot: ${visualize_right_2d}

# 相机
  - 
    _target_: openteach.components.visualizers.image.RobotImageVisualizer
    host: ${host_address}
    cam_port_offset: ${cam_port_offset}
    cam_id: 1  # 使用第一个摄像头

# Operators used to retarget the keypoints
operators:
  - 
    _target_: openteach.components.operators.piper.PiperArmOperator
    host: ${host_address}
    transformed_keypoints_port: ${transformed_position_keypoint_port}
    arm_resolution_port: ${resolution_button_publish_port}
    use_filter: True
    teleoperation_reset_port: ${teleop_reset_publish_port}

# List of controller classes used
controllers:
  -
    _target_: openteach.robot.piper.PiperArm

# 添加 GeminiCameras 配置
sensors:
  -
    _target_: openteach.components.sensors.gemini.GeminiCamera
    stream_configs:
      host: ${host_address}
      port: ${cam_port_offset}
    cam_serial_num: "145645318"  # 替换为您的相机序列号
    cam_id: 0
    cam_configs:
      rotation_angle: 0
      width: 640
      height: 360
    stream_oculus: true

# Information to be recorded by the robot 
recorded_data:
  - 
    - joint_states
    - cartesian_states